name: main-build

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build main branch
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 18
      target-build: true
      target-lint: true
      target-unit-tests: true
      stage: tst
  